test

diff --git a/.github/workflows/check-name.yml b/.github/workflows/check-name.yml
--- a/.github/workflows/check-name.yml
+++ b/.github/workflows/check-name.yml
@@ -15,9 +15,7 @@ jobs:
           msg: ${{ env.BRANCH_NAME }}
           separator: "/"
           maxsplit: -1
-        env:
-          BRANCH_PREFIX: ${{ steps.split.outputs._0 }}
       - name: Check branch naming
-        if: false == (contains(fromJson('["feat", "fix"]'), ${{ env.BRANCH_PREFIX }}))
-        run: echo "::error::Prefix ${{ env.BRANCH_PREFIX }} doesn't match possible branch prefixes" && exit 1
+        if: false == (contains(fromJson('["feat", "fix"]'), ${{ steps.split.outputs._0 }}))
+        run: echo "::error::Prefix ${{ steps.split.outputs._0 }} doesn't match possible branch prefixes" && exit 1
         
