Testing

diff --git a/.github/workflows/check-name.yml b/.github/workflows/check-name.yml
--- a/.github/workflows/check-name.yml
+++ b/.github/workflows/check-name.yml
@@ -9,20 +9,19 @@ jobs:
     name: Check branch name
     runs-on: ubuntu-20.04
     steps:
-      - uses: jungwinter/split@master
-        id: split
-        with:
-          msg: ${{ env.BRANCH_NAME }}
-          separator: "/"
-          maxsplit: -1
+    - name: "Get the prefix of the branch"
+      if: github.ref_type == 'branch'
+      shell: bash
+      run: |
+        branch_prefix=$(cut -d '/' -f 1)
+        echo "BRANCH_PREFIX=$branch_prefix" >> $GITHUB_ENV
+    - name: Check branch name has slash
+      if: contains(env.BRANCH_NAME, '/') == false
+      run: echo "[ERROR] Branch name ${{ env.BRANCH_NAME }} does not contain a prefix and a backslash." && exit 1
 
-      - name: Check branch name has slash
-        if: contains(env.BRANCH_NAME, '/') == false
-        run: echo "[ERROR] Branch name ${{ env.BRANCH_NAME }} does not contain a prefix and a backslash." && exit 1
-
-      - name: Check branch prefix naming
-        if: contains(fromJson('["fix", "feat", "junk", "maint", "doc", "no-ci", "testing", "release"]'), steps.split.outputs._0) == false
-        run: echo "[ERROR] Branch name ${{ env.BRANCH_NAME }} prefix is not valid." && exit 1
+    - name: Check branch prefix naming
+      if: contains(fromJson('["fix", "feat", "junk", "maint", "doc", "no-ci", "testing", "release"]'), steps.split.outputs._0) == false
+      run: echo "[ERROR] Branch name ${{ env.BRANCH_NAME }} prefix is not valid." && exit 1
 
   check-pr-title:
     runs-on: ubuntu-latest
