test

diff --git a/.github/workflows/check-name.yml b/.github/workflows/check-name.yml
--- a/.github/workflows/check-name.yml
+++ b/.github/workflows/check-name.yml
@@ -17,7 +17,7 @@ jobs:
         echo "BRANCH_PREFIX=$branch_prefix" >> $GITHUB_ENV
     - name: Check branch name has slash
       if: contains(${{ github.head_ref || github.ref_name }}, '/') == false
-      run: echo "[ERROR] Branch name ${{ env.BRANCH_NAME }} does not contain a prefix and a backslash." && exit 1
+      run: echo "[ERROR] Branch name ${{ github.head_ref || github.ref_name }} does not contain a prefix and a backslash." && exit 1
 
     - name: Check branch prefix naming
       if: contains(fromJson('["fix", "feat", "junk", "maint", "doc", "no-ci", "testing", "release"]'), env.BRANCH_PREFIX) == false
